### ISSUE TITLE
Instantiation may use different rounding for glyph bounding boxes than rest of fontTools

### ISSUE THREAD

**Issue by madig** [googlefonts/fontmake#558]
In a project of ours, a compiled-to-TTF instance was failing Font Validator with error E1112, "Bounding box is incorrect, Composite Maximal deviation=1(FU)", for various composites. Opening and saving the TTFs with recalculation of bounding boxes turned on solved the problem by presumably fixing off-by-ones.

Todo: invent reproduction case.

**Comment by anthrotype** [comment]
no bug without repro

**Comment by weiweihuanghuang** [comment]
I am getting the same error in my current project, how do I fix this issue?

**Comment by madig** [comment]
I thought this was fixed in the most up to date fontTools. Try running fontmake with `--round-instances`, this avoids the problem entirely but may invalidate VTT hinting.

**Comment by weiweihuanghuang** [comment]
I ran fontmake with `--round-instances` but I still get the error, I will create an issue with the font project once it's public

**Comment by anthrotype** [comment]
I think this issue with composites' bounding boxes was already fixed. Here's the relevant issues/PRs:
https://github.com/googlefonts/fontmake/issues/593
https://github.com/fonttools/fonttools/pull/1763
https://github.com/googlefonts/ufo2ft/pull/356

@weiweihuanghuang maybe you can send me a copy privately?
