### ISSUE TITLE
Error on Generating Variable Font

### ISSUE THREAD

**Issue by aminabedi68** [googlefonts/fontmake#651]
hi
I'm recently working on a font in fontforge and want to generate a simple variable version (2 masters across 1 axis, 2nd master is the same with a bit design change in 3 glyphs) but fontmake show me an error and stop working, here is the log:
```
INFO:fontmake.font_project:Building variable font variable_ttf\Pinar-VF.ttf
INFO:ufo2ft:Pre-processing glyphs
INFO:cu2qu.ufo:New spline lengths: 1: 315, 2: 1257, 3: 397, 4: 189, 5: 34, 6: 6
INFO:ufo2ft.filters:Running DecomposeComponentsFilter on Pinar-Light
INFO:ufo2ft.filters:Running DecomposeComponentsFilter on Pinar-Bold
INFO:ufo2ft:Building OpenType tables for Pinar-Light
fontmake: Error: In 'Pinar.designspace': Generating fonts from Designspace failed: [<fontTools.feaLib.ast.GlyphClass object at 0x03F86270>]
```
unfortunately I can't share the source but I realize fontmake working fine when I delete one of my GSUB ```calt``` lookup.

**Comment by madig** [comment]
You're seeing an uncommented assertion error from within feaLib. The `calt` lookup is the key here, feaLib doesn't like it for some reason. Can you please post it?

**Comment by anthrotype** [comment]
maybe it's hitting that bare assertion that @tomarcher101 fixed in https://github.com/fonttools/fonttools/pull/1876

@aminabedi68 can you please try to update fonttools `pip install -U fonttools` and retry?

**Comment by aminabedi68** [comment]
still not working (after updating fonttools to 4.8.1 and using python 3)
```
INFO:fontmake.font_project:Building variable font variable_ttf\Pinar-VF.ttf
INFO:ufo2ft:Pre-processing glyphs
INFO:cu2qu.ufo:New spline lengths: 1: 315, 2: 1257, 3: 397, 4: 189, 5: 34, 6: 6
INFO:ufo2ft.filters:Running DecomposeComponentsFilter on Pinar-Light
INFO:ufo2ft.filters:Running DecomposeComponentsFilter on Pinar-Bold
INFO:ufo2ft:Building OpenType tables for Pinar-Light
fontmake: Error: In 'Pinar.designspace': Generating fonts from Designspace failed: E:/Design/Fonts/My Fonts/Pinar/Pinar-light.ufo:171:5: Invalid substitution statement
```

**Comment by anthrotype** [comment]
exactly, it is "invalid". Look at the statement at line 171 to see if it looks correct to you.
Maybe you forgot an apostrophe?

**Comment by anthrotype** [comment]
the error message `Pinar-light.ufo:171:5: Invalid substitution statement` is saying that at line 171 (character 5) of the features's text there is an invalid substitution statement.

**Comment by anthrotype** [comment]
@madig I suggest fontmake (or ufo2ft) reraises FeatureLibError so that we re can reformat the error message to make it clearer those numbers are the position of the invalid statement in the UFO's features.fea text.

**Comment by aminabedi68** [comment]
yes! thank you, you right @anthrotype ! the error, related to an extra apostrophe, but in all tests, I haven't seen an error.
